"""add index on jobs role

Revision ID: 58d7e1ab906e
Revises: 4b4d4ce80ca8
Create Date: 2026-07-13 01:25:37.929156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d7e1ab906e'
down_revision: Union[str, Sequence[str], None] = '4b4d4ce80ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_role'), 'jobs', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_role'), table_name='jobs')
    # ### end Alembic commands ###
