""" renamed schema_json to form_schema_json

Revision ID: 91481df17212
Revises: f6b3a8dc8ea2
Create Date: 2026-06-29 22:15:23.692031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91481df17212'
down_revision: Union[str, Sequence[str], None] = 'f6b3a8dc8ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('form_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('forms', 'schema_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('forms', 'form_schema_json')
    # ### end Alembic commands ###
