"""initial tables

Revision ID: c44132e1775b
Revises: 
Create Date: 2026-06-23 23:49:28.646422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44132e1775b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('LINKEDIN', 'GOOGLE', name='providertype'), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'agent_name', name='uq_user_provider_agent')
    )
    op.create_index(op.f('ix_connected_accounts_agent_name'), 'connected_accounts', ['agent_name'], unique=False)
    op.create_index(op.f('ix_connected_accounts_provider'), 'connected_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('linkedin_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connected_account_id', sa.Integer(), nullable=False),
    sa.Column('person_urn', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_identities_connected_account_id'), 'linkedin_identities', ['connected_account_id'], unique=True)
    op.create_index(op.f('ix_linkedin_identities_person_urn'), 'linkedin_identities', ['person_urn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_identities_person_urn'), table_name='linkedin_identities')
    op.drop_index(op.f('ix_linkedin_identities_connected_account_id'), table_name='linkedin_identities')
    op.drop_table('linkedin_identities')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_provider'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_agent_name'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
