"""add title to linkedin_post_drafts

Revision ID: eb148a8a2280
Revises: ce6f3e128f09
Create Date: 2026-07-14 09:11:16.364707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb148a8a2280'
down_revision: Union[str, Sequence[str], None] = 'ce6f3e128f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_post_drafts', sa.Column('title', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_linkedin_post_drafts_title'), 'linkedin_post_drafts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_post_drafts_title'), table_name='linkedin_post_drafts')
    op.drop_column('linkedin_post_drafts', 'title')
    # ### end Alembic commands ###
