"""renamed the connected accounts agent name column to integration name

Revision ID: eb56d9e17a7a
Revises: 91481df17212
Create Date: 2026-07-01 00:29:20.676748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb56d9e17a7a'
down_revision: Union[str, Sequence[str], None] = '91481df17212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('integration_name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_connected_accounts_agent_name'), table_name='connected_accounts')
    op.drop_constraint(op.f('uq_user_provider_agent'), 'connected_accounts', type_='unique')
    op.create_index(op.f('ix_connected_accounts_integration_name'), 'connected_accounts', ['integration_name'], unique=False)
    op.create_unique_constraint('uq_user_provider_integration', 'connected_accounts', ['user_id', 'provider', 'integration_name'])
    op.drop_column('connected_accounts', 'agent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_provider_integration', 'connected_accounts', type_='unique')
    op.drop_index(op.f('ix_connected_accounts_integration_name'), table_name='connected_accounts')
    op.create_unique_constraint(op.f('uq_user_provider_agent'), 'connected_accounts', ['user_id', 'provider', 'agent_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_connected_accounts_agent_name'), 'connected_accounts', ['agent_name'], unique=False)
    op.drop_column('connected_accounts', 'integration_name')
    # ### end Alembic commands ###
