"""adding a form model

Revision ID: f6b3a8dc8ea2
Revises: fc78f02afb4f
Create Date: 2026-06-29 14:35:13.027794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b3a8dc8ea2'
down_revision: Union[str, Sequence[str], None] = 'fc78f02afb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('form_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='formstatus'), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_foreign_key(None, 'applications', 'forms', ['form_id'], ['form_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'form_links', 'forms', ['form_id'], ['form_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'form_questions', 'forms', ['form_id'], ['form_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_questions', type_='foreignkey')
    op.drop_constraint(None, 'form_links', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_table('forms')
    # ### end Alembic commands ###
